# -*- coding: utf-8 -*-
"""Untitled3.ipynb

Automatically generated by Colab.

Original file is located at
    https://colab.research.google.com/drive/1QgfiByonAOYRkFpt-kypgVN34dR-42ZM
"""

import pandas as pd
baza={
    "FISH":[ "Aliyev Ali","Aliyeva Dilyora","Ergashev Shazboz","Hamidov Abdulaziz"  ],
    "Yoshi":[ "11","16","19","19" ],
    "Jinsi":["erkak","ayol","erkak","erkak" ],
    "Maktabi":["2-maktak","Priziden maktabi","26-maktak","28-maktak" ],
    "Manzili":["Farg'ona shahar","Andijon shahar","Andijon shahar","Farg'ona shahar" ],
    "Tel raqami":["99 30 22 12","91 123 45 67","94 360 37 70","91 391 71 72" ]
}
db=pd.DataFrame(baza)
print(db)

filtr=db[db['Jinsi']=="ayol"]
print(filtr)

filtr=db[(db['Jinsi']=="ayol")&(db["Yoshi"]>"15")]
print(filtr)